# Generated by Django 3.0.7 on 2020-07-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseuser',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='male', max_length=20),
        ),
    ]
