# Generated by Django 3.0.7 on 2020-07-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_exerciseuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
